# @format

version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - './src:/app/src'
      - '/var/run/docker.sock'
    env_file: dev.env
