# @format

version: '3.8'

services:
  server:
    user: '1000:1000'
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - './src:/app/src'
    env_file: dev.env
